{
 "title": "Product dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"rs-product\"}[30s])) by (app,path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests per second per Istance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"rs-product\"}[30s])) / sum(up{service=\"rs-product\"})",
     "legendFormat": "rps"
    },
    {
     "expr": "sum(up{service=\"rs-product\"})",
     "legendFormat": "instance"
    }
   ]
  },
  {
   "title": "Instance Number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{service=\"rs-product\"})"
    }
   ]
  },
  {
   "title": "Requests 200 OK per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"rs-product\",status_code=\"200\"}[30s])) by (app,path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code!=\"200\",service=\"rs-product\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(http_request_duration_seconds_count{service=\"rs-product\"}[1m] ) ) by (status_code)",
     "legendFormat": "HTTP {{ status_code }}"
    }
   ]
  },
  {
   "title": "Requests under 300ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(increase(http_request_duration_seconds_bucket{status_code=\"200\",le=\"0.3\",service=\"rs-product\"}[30s]) \n/ ignoring (le) increase(http_request_duration_seconds_count{status_code=\"200\",service=\"rs-product\"}[30s])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{status_code=\"200\",service=\"rs-product\"}[30s])\n/\nrate(http_request_duration_seconds_count{status_code=\"200\",service=\"rs-product\"}[30s])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", container_name!=\"POD\",container_name=\"rs-product\"}[1m]))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{job=\"kubelet\", container_name=\"rs-product\", container_name!=\"POD\"})",
     "legendFormat": "mem"
    },
    {
     "expr": "sum by(container_name) (kube_pod_container_resource_requests_memory_bytes{job=\"kube-state-metrics\", container=\"rs-product\"})",
     "legendFormat": "requested"
    }
   ]
  }
 ]
}