kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: rs-product-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-product
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: rs-product
      metricName: http_request_rate_per_second
      targetValue: 1